/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: chat.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "chat.pb-c.h"
void   chat__user_registration__init
                     (Chat__UserRegistration         *message)
{
  static const Chat__UserRegistration init_value = CHAT__USER_REGISTRATION__INIT;
  *message = init_value;
}
size_t chat__user_registration__get_packed_size
                     (const Chat__UserRegistration *message)
{
  assert(message->base.descriptor == &chat__user_registration__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t chat__user_registration__pack
                     (const Chat__UserRegistration *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &chat__user_registration__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t chat__user_registration__pack_to_buffer
                     (const Chat__UserRegistration *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &chat__user_registration__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Chat__UserRegistration *
       chat__user_registration__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Chat__UserRegistration *)
     protobuf_c_message_unpack (&chat__user_registration__descriptor,
                                allocator, len, data);
}
void   chat__user_registration__free_unpacked
                     (Chat__UserRegistration *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &chat__user_registration__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   chat__change_status__init
                     (Chat__ChangeStatus         *message)
{
  static const Chat__ChangeStatus init_value = CHAT__CHANGE_STATUS__INIT;
  *message = init_value;
}
size_t chat__change_status__get_packed_size
                     (const Chat__ChangeStatus *message)
{
  assert(message->base.descriptor == &chat__change_status__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t chat__change_status__pack
                     (const Chat__ChangeStatus *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &chat__change_status__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t chat__change_status__pack_to_buffer
                     (const Chat__ChangeStatus *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &chat__change_status__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Chat__ChangeStatus *
       chat__change_status__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Chat__ChangeStatus *)
     protobuf_c_message_unpack (&chat__change_status__descriptor,
                                allocator, len, data);
}
void   chat__change_status__free_unpacked
                     (Chat__ChangeStatus *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &chat__change_status__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   chat__message__init
                     (Chat__Message         *message)
{
  static const Chat__Message init_value = CHAT__MESSAGE__INIT;
  *message = init_value;
}
size_t chat__message__get_packed_size
                     (const Chat__Message *message)
{
  assert(message->base.descriptor == &chat__message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t chat__message__pack
                     (const Chat__Message *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &chat__message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t chat__message__pack_to_buffer
                     (const Chat__Message *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &chat__message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Chat__Message *
       chat__message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Chat__Message *)
     protobuf_c_message_unpack (&chat__message__descriptor,
                                allocator, len, data);
}
void   chat__message__free_unpacked
                     (Chat__Message *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &chat__message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   chat__user_information__init
                     (Chat__UserInformation         *message)
{
  static const Chat__UserInformation init_value = CHAT__USER_INFORMATION__INIT;
  *message = init_value;
}
size_t chat__user_information__get_packed_size
                     (const Chat__UserInformation *message)
{
  assert(message->base.descriptor == &chat__user_information__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t chat__user_information__pack
                     (const Chat__UserInformation *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &chat__user_information__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t chat__user_information__pack_to_buffer
                     (const Chat__UserInformation *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &chat__user_information__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Chat__UserInformation *
       chat__user_information__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Chat__UserInformation *)
     protobuf_c_message_unpack (&chat__user_information__descriptor,
                                allocator, len, data);
}
void   chat__user_information__free_unpacked
                     (Chat__UserInformation *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &chat__user_information__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   chat__user_request__init
                     (Chat__UserRequest         *message)
{
  static const Chat__UserRequest init_value = CHAT__USER_REQUEST__INIT;
  *message = init_value;
}
size_t chat__user_request__get_packed_size
                     (const Chat__UserRequest *message)
{
  assert(message->base.descriptor == &chat__user_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t chat__user_request__pack
                     (const Chat__UserRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &chat__user_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t chat__user_request__pack_to_buffer
                     (const Chat__UserRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &chat__user_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Chat__UserRequest *
       chat__user_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Chat__UserRequest *)
     protobuf_c_message_unpack (&chat__user_request__descriptor,
                                allocator, len, data);
}
void   chat__user_request__free_unpacked
                     (Chat__UserRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &chat__user_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   chat__connected_users__init
                     (Chat__ConnectedUsers         *message)
{
  static const Chat__ConnectedUsers init_value = CHAT__CONNECTED_USERS__INIT;
  *message = init_value;
}
size_t chat__connected_users__get_packed_size
                     (const Chat__ConnectedUsers *message)
{
  assert(message->base.descriptor == &chat__connected_users__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t chat__connected_users__pack
                     (const Chat__ConnectedUsers *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &chat__connected_users__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t chat__connected_users__pack_to_buffer
                     (const Chat__ConnectedUsers *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &chat__connected_users__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Chat__ConnectedUsers *
       chat__connected_users__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Chat__ConnectedUsers *)
     protobuf_c_message_unpack (&chat__connected_users__descriptor,
                                allocator, len, data);
}
void   chat__connected_users__free_unpacked
                     (Chat__ConnectedUsers *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &chat__connected_users__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   chat__client_request__init
                     (Chat__ClientRequest         *message)
{
  static const Chat__ClientRequest init_value = CHAT__CLIENT_REQUEST__INIT;
  *message = init_value;
}
size_t chat__client_request__get_packed_size
                     (const Chat__ClientRequest *message)
{
  assert(message->base.descriptor == &chat__client_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t chat__client_request__pack
                     (const Chat__ClientRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &chat__client_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t chat__client_request__pack_to_buffer
                     (const Chat__ClientRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &chat__client_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Chat__ClientRequest *
       chat__client_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Chat__ClientRequest *)
     protobuf_c_message_unpack (&chat__client_request__descriptor,
                                allocator, len, data);
}
void   chat__client_request__free_unpacked
                     (Chat__ClientRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &chat__client_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   chat__server_response__init
                     (Chat__ServerResponse         *message)
{
  static const Chat__ServerResponse init_value = CHAT__SERVER_RESPONSE__INIT;
  *message = init_value;
}
size_t chat__server_response__get_packed_size
                     (const Chat__ServerResponse *message)
{
  assert(message->base.descriptor == &chat__server_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t chat__server_response__pack
                     (const Chat__ServerResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &chat__server_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t chat__server_response__pack_to_buffer
                     (const Chat__ServerResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &chat__server_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Chat__ServerResponse *
       chat__server_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Chat__ServerResponse *)
     protobuf_c_message_unpack (&chat__server_response__descriptor,
                                allocator, len, data);
}
void   chat__server_response__free_unpacked
                     (Chat__ServerResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &chat__server_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor chat__user_registration__field_descriptors[2] =
{
  {
    "usarname",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Chat__UserRegistration, usarname),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ip",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Chat__UserRegistration, ip),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned chat__user_registration__field_indices_by_name[] = {
  1,   /* field[1] = ip */
  0,   /* field[0] = usarname */
};
static const ProtobufCIntRange chat__user_registration__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor chat__user_registration__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "chat.UserRegistration",
  "UserRegistration",
  "Chat__UserRegistration",
  "chat",
  sizeof(Chat__UserRegistration),
  2,
  chat__user_registration__field_descriptors,
  chat__user_registration__field_indices_by_name,
  1,  chat__user_registration__number_ranges,
  (ProtobufCMessageInit) chat__user_registration__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor chat__change_status__field_descriptors[2] =
{
  {
    "username",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Chat__ChangeStatus, username),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "status",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Chat__ChangeStatus, status),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned chat__change_status__field_indices_by_name[] = {
  1,   /* field[1] = status */
  0,   /* field[0] = username */
};
static const ProtobufCIntRange chat__change_status__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor chat__change_status__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "chat.ChangeStatus",
  "ChangeStatus",
  "Chat__ChangeStatus",
  "chat",
  sizeof(Chat__ChangeStatus),
  2,
  chat__change_status__field_descriptors,
  chat__change_status__field_indices_by_name,
  1,  chat__change_status__number_ranges,
  (ProtobufCMessageInit) chat__change_status__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor chat__message__field_descriptors[3] =
{
  {
    "receiver",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Chat__Message, receiver),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sender",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Chat__Message, sender),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "text",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Chat__Message, text),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned chat__message__field_indices_by_name[] = {
  0,   /* field[0] = receiver */
  1,   /* field[1] = sender */
  2,   /* field[2] = text */
};
static const ProtobufCIntRange chat__message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor chat__message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "chat.Message",
  "Message",
  "Chat__Message",
  "chat",
  sizeof(Chat__Message),
  3,
  chat__message__field_descriptors,
  chat__message__field_indices_by_name,
  1,  chat__message__number_ranges,
  (ProtobufCMessageInit) chat__message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor chat__user_information__field_descriptors[3] =
{
  {
    "username",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Chat__UserInformation, username),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ip",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Chat__UserInformation, ip),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "status",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Chat__UserInformation, status),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned chat__user_information__field_indices_by_name[] = {
  1,   /* field[1] = ip */
  2,   /* field[2] = status */
  0,   /* field[0] = username */
};
static const ProtobufCIntRange chat__user_information__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor chat__user_information__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "chat.UserInformation",
  "UserInformation",
  "Chat__UserInformation",
  "chat",
  sizeof(Chat__UserInformation),
  3,
  chat__user_information__field_descriptors,
  chat__user_information__field_indices_by_name,
  1,  chat__user_information__number_ranges,
  (ProtobufCMessageInit) chat__user_information__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor chat__user_request__field_descriptors[1] =
{
  {
    "user",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Chat__UserRequest, user),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned chat__user_request__field_indices_by_name[] = {
  0,   /* field[0] = user */
};
static const ProtobufCIntRange chat__user_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor chat__user_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "chat.UserRequest",
  "UserRequest",
  "Chat__UserRequest",
  "chat",
  sizeof(Chat__UserRequest),
  1,
  chat__user_request__field_descriptors,
  chat__user_request__field_indices_by_name,
  1,  chat__user_request__number_ranges,
  (ProtobufCMessageInit) chat__user_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor chat__connected_users__field_descriptors[1] =
{
  {
    "users",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Chat__ConnectedUsers, n_users),
    offsetof(Chat__ConnectedUsers, users),
    &chat__user_information__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned chat__connected_users__field_indices_by_name[] = {
  0,   /* field[0] = users */
};
static const ProtobufCIntRange chat__connected_users__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor chat__connected_users__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "chat.ConnectedUsers",
  "ConnectedUsers",
  "Chat__ConnectedUsers",
  "chat",
  sizeof(Chat__ConnectedUsers),
  1,
  chat__connected_users__field_descriptors,
  chat__connected_users__field_indices_by_name,
  1,  chat__connected_users__number_ranges,
  (ProtobufCMessageInit) chat__connected_users__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue chat__client_request__option__enum_values_by_number[5] =
{
  { "USER_LOGIN", "CHAT__CLIENT_REQUEST__OPTION__USER_LOGIN", 0 },
  { "CONNECTED_USERS", "CHAT__CLIENT_REQUEST__OPTION__CONNECTED_USERS", 1 },
  { "USER_INFORMATION", "CHAT__CLIENT_REQUEST__OPTION__USER_INFORMATION", 2 },
  { "STATUS_CHANGE", "CHAT__CLIENT_REQUEST__OPTION__STATUS_CHANGE", 3 },
  { "SEND_MESSAGE", "CHAT__CLIENT_REQUEST__OPTION__SEND_MESSAGE", 4 },
};
static const ProtobufCIntRange chat__client_request__option__value_ranges[] = {
{0, 0},{0, 5}
};
static const ProtobufCEnumValueIndex chat__client_request__option__enum_values_by_name[5] =
{
  { "CONNECTED_USERS", 1 },
  { "SEND_MESSAGE", 4 },
  { "STATUS_CHANGE", 3 },
  { "USER_INFORMATION", 2 },
  { "USER_LOGIN", 0 },
};
const ProtobufCEnumDescriptor chat__client_request__option__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "chat.ClientRequest.Option",
  "Option",
  "Chat__ClientRequest__Option",
  "chat",
  5,
  chat__client_request__option__enum_values_by_number,
  5,
  chat__client_request__option__enum_values_by_name,
  1,
  chat__client_request__option__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor chat__client_request__field_descriptors[5] =
{
  {
    "option",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Chat__ClientRequest, has_option),
    offsetof(Chat__ClientRequest, option),
    &chat__client_request__option__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "newuser",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Chat__ClientRequest, newuser),
    &chat__user_registration__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "user",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Chat__ClientRequest, user),
    &chat__user_request__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "status",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Chat__ClientRequest, status),
    &chat__change_status__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "messg",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Chat__ClientRequest, messg),
    &chat__message__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned chat__client_request__field_indices_by_name[] = {
  4,   /* field[4] = messg */
  1,   /* field[1] = newuser */
  0,   /* field[0] = option */
  3,   /* field[3] = status */
  2,   /* field[2] = user */
};
static const ProtobufCIntRange chat__client_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor chat__client_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "chat.ClientRequest",
  "ClientRequest",
  "Chat__ClientRequest",
  "chat",
  sizeof(Chat__ClientRequest),
  5,
  chat__client_request__field_descriptors,
  chat__client_request__field_indices_by_name,
  1,  chat__client_request__number_ranges,
  (ProtobufCMessageInit) chat__client_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue chat__server_response__option__enum_values_by_number[5] =
{
  { "USER_LOGIN", "CHAT__SERVER_RESPONSE__OPTION__USER_LOGIN", 0 },
  { "CONNECTED_USERS", "CHAT__SERVER_RESPONSE__OPTION__CONNECTED_USERS", 1 },
  { "USER_INFORMATION", "CHAT__SERVER_RESPONSE__OPTION__USER_INFORMATION", 2 },
  { "STATUS_CHANGE", "CHAT__SERVER_RESPONSE__OPTION__STATUS_CHANGE", 3 },
  { "SEND_MESSAGE", "CHAT__SERVER_RESPONSE__OPTION__SEND_MESSAGE", 4 },
};
static const ProtobufCIntRange chat__server_response__option__value_ranges[] = {
{0, 0},{0, 5}
};
static const ProtobufCEnumValueIndex chat__server_response__option__enum_values_by_name[5] =
{
  { "CONNECTED_USERS", 1 },
  { "SEND_MESSAGE", 4 },
  { "STATUS_CHANGE", 3 },
  { "USER_INFORMATION", 2 },
  { "USER_LOGIN", 0 },
};
const ProtobufCEnumDescriptor chat__server_response__option__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "chat.ServerResponse.Option",
  "Option",
  "Chat__ServerResponse__Option",
  "chat",
  5,
  chat__server_response__option__enum_values_by_number,
  5,
  chat__server_response__option__enum_values_by_name,
  1,
  chat__server_response__option__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue chat__server_response__code__enum_values_by_number[2] =
{
  { "FAILED_OPERATION", "CHAT__SERVER_RESPONSE__CODE__FAILED_OPERATION", 0 },
  { "SUCCESSFUL_OPERATION", "CHAT__SERVER_RESPONSE__CODE__SUCCESSFUL_OPERATION", 1 },
};
static const ProtobufCIntRange chat__server_response__code__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex chat__server_response__code__enum_values_by_name[2] =
{
  { "FAILED_OPERATION", 0 },
  { "SUCCESSFUL_OPERATION", 1 },
};
const ProtobufCEnumDescriptor chat__server_response__code__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "chat.ServerResponse.Code",
  "Code",
  "Chat__ServerResponse__Code",
  "chat",
  2,
  chat__server_response__code__enum_values_by_number,
  2,
  chat__server_response__code__enum_values_by_name,
  1,
  chat__server_response__code__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor chat__server_response__field_descriptors[7] =
{
  {
    "option",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Chat__ServerResponse, has_option),
    offsetof(Chat__ServerResponse, option),
    &chat__server_response__option__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "code",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Chat__ServerResponse, has_code),
    offsetof(Chat__ServerResponse, code),
    &chat__server_response__code__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "response",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Chat__ServerResponse, response),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "users",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Chat__ServerResponse, users),
    &chat__connected_users__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "user",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Chat__ServerResponse, user),
    &chat__user_information__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "messg",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Chat__ServerResponse, messg),
    &chat__message__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "status",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Chat__ServerResponse, status),
    &chat__change_status__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned chat__server_response__field_indices_by_name[] = {
  1,   /* field[1] = code */
  5,   /* field[5] = messg */
  0,   /* field[0] = option */
  2,   /* field[2] = response */
  6,   /* field[6] = status */
  4,   /* field[4] = user */
  3,   /* field[3] = users */
};
static const ProtobufCIntRange chat__server_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor chat__server_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "chat.ServerResponse",
  "ServerResponse",
  "Chat__ServerResponse",
  "chat",
  sizeof(Chat__ServerResponse),
  7,
  chat__server_response__field_descriptors,
  chat__server_response__field_indices_by_name,
  1,  chat__server_response__number_ranges,
  (ProtobufCMessageInit) chat__server_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
